FROM --platform=linux/amd64 ubuntu:24.04 AS build

# Environment variables
ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.7.1 \
    CELERY_APP=todo.tasks.ical \
    CELERY_LOGLEVEL=info \
    PATH="/venv/bin:$PATH"

# Install system dependencies and Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    build-essential \
    wget \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    libpq-dev \
    libjpeg-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libblas-dev \
    liblapack-dev \
    steghide \
    && rm -rf /var/lib/apt/lists/*

# Create and activate a Python virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Poetry
RUN pip install --upgrade pip && pip install poetry

# Set working directory to /app
WORKDIR /app
COPY pyproject.toml poetry.lock ./

# Install dependencies using Poetry
RUN poetry install --no-root --no-interaction

# Copy the "todo" folder to the container
COPY . /app
COPY start-celery.sh /app/start-celery.sh
COPY aws.env /app/aws.env

RUN ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "amd64" ]; then \
        wget https://github.com/CSSE6400/CoughOverflow-Engine/releases/download/v1.0/overflowengine-amd64 -O overflowengine; \
    else \
        wget https://github.com/CSSE6400/CoughOverflow-Engine/releases/download/v1.0/overflowengine-arm64 -O overflowengine; \
    fi && chmod +x /app/overflowengine


#RUN poetry add "celery[sqs]" boto3 botocore
# Set up the Celery app environment variable
ENV CELERY_APP=todo.tasks.ical

# Make the start script executable
RUN chmod +x /app/start-celery.sh

# Set the entry point to run the Celery worker
ENTRYPOINT ["/bin/bash", "-c", "/app/start-celery.sh"]
